### ISSUE TITLE
[AppImage] HowTo install file browser extension packages manually

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs-client-desktop#267]
This isn't enough explanation for me:

> The file browser integration, which means overlay icons and the context menu, is not included in the AppImage. You need to install file browser extension packages manually.

(from https://doc.owncloud.com/desktop/2.11/installing.html#appimage)

@fmoc could you post the instructions?

**Comment by fmoc** [comment]
A link to the installation docs should do.

**Comment by mmattel** [comment]
> A link to the installation docs should do.

@fmoc can you support with the correct link / description?
I can start fixing afterwards

> we could extend this section to cover the extensions more extensively.

for sure a good idea to reduce confusion or possible questions

**Comment by mmattel** [comment]
Update: based on a discussion between me and @fmoc today, we decided that it would be best creating a script to install the extension packs covereing the majority of users. @fmoc will create that script, the location is tbd, when available, will reference it in the docs.

**Comment by fmoc** [comment]
The script will prefer to install our packages (if found, i.e., the user added the repository), otherwise fall back to the distro packages (if available), otherwise suggest adding our repository. We'll link to the download page, e.g., https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/.

The download page will have to be adjusted, too, to highlight that installing the `owncloud-client` package is just one option. I'd suggest extracting the install command into a third "code section".
