### ISSUE TITLE
[4.1] [owncloudcmd] from [AppImage]

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs-client-desktop#427]
- https://github.com/owncloud/client/issues/10888
- https://github.com/owncloud/craft-blueprints-owncloud/pull/32

Please extend this page:
- https://doc.owncloud.com/desktop/next/advanced_usage/command_line_client.html

**Comment by michaelstingl** [comment]
@fmoc could you post the new syntax to start this?

**Comment by fmoc** [comment]
Clarify what exactly? I don't understand your question.

When you used to run the AppImage, it worked like you were calling the contained `owncloud` binary. This is due to the fact that we more or less directly forwarded all CLI parameters (if any were passed) directly to that binary internally. There was no difference between calling `ownCloud.AppImage` and `owncloud` from a user perspective.

In 4.1, we want to give users a chance to call the commandline client easily, too. Therefore, the AppImage checks if a `--cmd` parameter is passed as the first parameter on the commandline. If yes, a shell script inside of the AppImage forwards the commandline parameters passed by the user to the `owncloudcmd` contained in the AppImage.

From a user perspective, `ownCloud.AppImage --cmd` works like calling `owncloudcmd` in a "traditional" setup, whereas `ownCloud.AppImage` (without `--cmd`) works like calling `owncloud` in a "traditional" setup.

In the future, there will be an `owncloud --cmd` that works like `owncloudcmd`, ultimately turning this current AppImage-only solution into a universal user experience shared on all platforms. Maybe we should have done that right away.

**Comment by mmattel** [comment]
This is the missing piece in understanding what is meant. It would be very helpful in adding such info  right at the beginning. Thanks for the clarification.

**Comment by fmoc** [comment]
Well,

> When --cmd is passed as the first parameter, the AppImage internally launches owncloudcmd, otherwise owncloud.

was pretty clear to me. It was just less elaborate.

**Comment by mmattel** [comment]
Q: are the [Command Line Parameters](https://doc.owncloud.com/desktop/4.0/advanced_usage/command_line_parameters.html) - not to confuse with [The Command Line Client](https://doc.owncloud.com/desktop/4.0/advanced_usage/command_line_client.html) - the same for AppImages ?

**Comment by saw-jan** [comment]
Docs looks good: https://doc.owncloud.com/desktop/next/advanced_usage/command_line_client.html 
https://github.com/owncloud/docs-client-desktop/pull/446#issuecomment-1617652126
